runtime: java17
instance_class: F1
resources:
  memory_gb: 1
env_variables:
  ADMIN_SECRET: $ADMIN_SECRET
  RECAPTCHA_SECRET: $RECAPTCHA_SECRET
  SENDGRID_API_KEY: $SENDGRID_API_KEY
  USERS_BUCKET: $USERS_BUCKET
  BLOCK_INDEXING: $BLOCK_INDEXING
  FORCE_HTTPS: $FORCE_HTTPS