<h2>J. Discipline</h2>
<p>All disciplinary matters in any way connected with the League or the conduct of matches played under the auspices of the
League shall be dealt with in accordance with the ECB's Model Disciplinary Rules which shall be deemed part of these
Rules and which shall prevail over any of the League's Rules which may overlap or be in conflict with the provisions of
such Model Rules.
<p>Any Club(s) with outstanding fines / hall hire charges not paid by 1st July after the close of the preceding season will incur
a deduction of eight points at the start of the new season.