<h2>L. Winding Up</h2>
<p>In the event of the League being wound up, a financial statement will be prepared and audited. If these accounts reveal
a deficit, every Member Club at the date of winding up, and every club which ceased to be in membership within the year
preceding the date of winding up, shall contribute equally to clear such deficiency. If a surplus is revealed, it shall be given
to some body with objects similar to those of the League, or if an alternative is necessary, then to some charitable body
preferably connected with cricket.