<h2>B. Aims and Objectives</h2>
<ol>
<li>The promotion, advancement and protection of the interests of cricket in Hampshire and its environs.
<li>Co-operation with the Hampshire Cricket Board, the Hampshire Cricket League and any other body having similar
objectives to the League.
<li>Co-operation with and the provision of assistance and advice to Member Clubs on any matter affecting the interests of
the Member Club or League.
<li>Consideration of any other means for promoting the interests of the League.
</ol>