<h2>B. Arrangement of Matches</h2>
<p>
Dates and times shall be decided by the Fixture Secretary and approved by the Committee. All Member Clubs shall be
notified by email when the fixtures are available on the website for their perusal. Any clashes or difficulties with dates
and times of their club's fixtures have to be notified to the Fixture Secretary in writing (email acceptable) within 14 days
of the publishing date otherwise, only in exceptional circumstances, will they be changed after this period has elapsed.