<h2>D. Promotion and Relegation</h2>
<p>The number of teams to be promoted and relegated between each pair of adjacent divisions shall be specified by the
Committee not later than the end of December in the relevant season. In the event of teams withdrawing from divisions
other than the bottom one, the Committee shall direct how the vacancies thus caused shall be filled; in general,
preference shall be given to promoting additional teams over not relegating relegated teams.
