<h2>H. Umpires and Scorers</h2>
<p>Umpires shall be appointed by the Committee unless clubs are advised to the contrary. Competent scorers will be provided
by the team and shall not be playing in the match. <a href="/resources">Match report sheets</a>
will be completed by the HOME team and will be
sent to the Fixture Secretary  
<@mailto address="fixturesec">by email,</@mailto> to be received by 9pm on the TUESDAY following the
match. The team
responsible for ensuring delivery should not assume that has happened until receipt is acknowledged or the result appears
on the website. In the event of the Fixture Secretary failing to receive the Match Report within this timescale, a
two point deduction will be made from the offending team’s league total.
<p>If a team fails to provide a competent scorer when the captain reports to the Umpires at the start of the match then he
shall nominate one of his players to act as scorer for the match and he shall not be allowed to take part in the match.