
name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the gcp-migration branch
  push:
    branches: [ gcp-migration ]
  pull_request:
    branches: [ gcp-migration ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate to App Engine
      id: 'auth'
      uses: 'google-github-actions/auth@v1.0.0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.8.2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"