
name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the test branch
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Replace variables
      uses: 73h/gae-app-yaml-replace-env-variables@v0.1
      env:
        ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
        RECAPTCHA_SECRET: ${{ secrets.RECAPTCHA_SECRET }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        USERS_BUCKET: sehicl-test-users
        BLOCK_INDEXING: true
      with:
        app_yaml_path: "app.yaml"

    - name: Authenticate to App Engine
      id: 'auth'
      uses: 'google-github-actions/auth@v1.0.0'
      with:
        credentials_json: '${{ secrets.GCP_TEST_CREDENTIALS }}'

    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.8.2
      with:
        project_id: ${{ secrets.GCP_TEST_PROJECT }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"